-- AlterTable
ALTER TABLE `run` ADD COLUMN `bossClearedCount` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `everBoss` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `lastBossConsumed` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `lastBossDay` INTEGER NOT NULL DEFAULT 0;
